import type { Config } from "tailwindcss";

// design tokens taken straight from your google stitch mockups.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb4a4",
        "surface-container-highest": "#e2e2e5",
        "on-tertiary-fixed-variant": "#48473f",
        background: "#f9f9fc",
        "tertiary-fixed": "#e6e2d7",
        "inverse-on-surface": "#f0f0f3",
        "secondary-container": "#fda18e",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#cac6bc",
        secondary: "#914a3b",
        "on-background": "#1a1c1e",
        "outline-variant": "#bfc8c9",
        "on-primary-fixed": "#002022",
        "on-secondary-fixed": "#3b0902",
        "on-tertiary-fixed": "#1c1c15",
        "inverse-primary": "#99d0d5",
        "primary-fixed-dim": "#99d0d5",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "surface-bright": "#f9f9fc",
        "surface-container-low": "#f3f3f6",
        "surface-dim": "#dadadc",
        outline: "#707979",
        primary: "#004449",
        "on-surface-variant": "#404849",
        "on-tertiary-container": "#ccc8be",
        "inverse-surface": "#2f3133",
        "surface-container": "#eeeef0",
        "primary-fixed": "#b5ecf2",
        "primary-container": "#245c61",
        "tertiary-container": "#56544c",
        "on-primary-fixed-variant": "#124e53",
        "secondary-fixed": "#ffdad3",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e8e8ea",
        tertiary: "#3e3d35",
        "surface-variant": "#e2e2e5",
        "on-secondary-container": "#773528",
        "on-surface": "#1a1c1e",
        "surface-tint": "#30666b",
        "on-primary-container": "#9cd2d8",
        surface: "#f9f9fc",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#743325",
        "status-running": "#004449",
        "status-done": "#48473f",
        "status-paused": "#914a3b",
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "0.75rem", xl: "1rem", full: "9999px" },
      spacing: {
        "container-max": "1280px",
        gutter: "32px",
        "section-gap": "160px",
        "margin-mobile": "24px",
        unit: "8px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
